### ISSUE TITLE
Admin Panel - Frontend copy username on click

### ISSUE THREAD

**Issue by maxonary** [maxonary/convitelist#22]
In case a user has registered the same username for two separate game types, clicking to copy a username will copy the first one the program finds (see code screenshot). 

The issue lies in the frontend userTable.tsx component in how the handleUsernameClick function works. It should instead identify the content to copy by a unique identifier. 

![IMG_3784](https://github.com/maxonary/convitelist/assets/62939182/75f2d6a6-8817-4d72-8d40-56f3c604223c)

https://github.com/maxonary/convitelist/assets/62939182/a2fe81f4-086e-427f-bd6c-d6fdf0be3bb2

**Comment by jobayer12** [comment]
@maxonary i would like to work on this task.
